---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: install tomcat9
    become: yes
    apt:  
      name: "{{ item }}"
      state: present
    with_items: 
      - tomcat9
      - maven
      - apache2


